LEVEL_MAP = [
'                                                                                                                                                               XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX          X',
'X                                                                                                                                                               XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX           X',
'X                                                                                                                                                                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX            X',
'X      XXXX                                                                                                                                                       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX            X',
'X  P                                                                                                                                                               XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX             X',
'XXXXX         XXX         XXX            XX   .                          X             XX                                           XXX                                                                                  X',
'XXXXX       XX                                             XXX          XXX          XXX   XXX                     XXXX   XXX   XX       XXXX  XXX  XX  XXX                                                              X',
'XXX    X  XXXX    XX  XX    XXX   XX   XXX   XXX     XXXX  XXX   XXX  XXXXXXX   XXX  XXX   XXX             X  XX          XXX   XX       XXXX  XXX  XX  XXX                                                              X',
'X      X  XXXX    XX  XXX        XX    XXX   XXX     XXXX  XXX   XXX  XXXXXXX   XXX  XXX   XXX  XXXXXXXXX  X  XX          XXX   XX       XXXX  XXX  XX  XXX   XXXXXXXX   XXXX     XXXX     XXXX    XXXXXXX  XXXXXX       X',  
'X   XXXX  XXXXXX  XX  XXXX       XX    XXX   XXX     XXXX  XXX   XXX  XXXXXXX   XXX  XXX   XXX  XXXXXXXXX  X  XX          XXX   XX       XXXX  XXX  XX  XXX   XXXXXXXX   XXXXX    XXXX     XXXX    XXXXXXX  XXXXXX       X',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   XXXX     XXXX    XXXXXXX  XXXXXX       X',
'X                                                                                                                                                                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX       X',
'X                                                                                                                                                                                                          XXXXXXX       X',
'X                                                                                                                                                                                                                        X',
'X      XXXXXXXXX  XX  XX         XX    XX                        XXX            XXX  XX                                                                                                                                  X',
'X      XXXXXXXXX  XX  XXX        XX    XXXX          XXXX  XXX   XXX  XXXXXXX   XXX  XXX   XXX  XXXXXXXXX  X  XX      XXX       XX       XXXX  XXX  XXXX     XXXXXXXX   XXXXXX   XXXX    XXX   XX  XXXXXXX               X',
'X      XXXXXXXXX  XX XXXXX       XX    XXXXX         XXXX  XXX   XXX  XXXXXXX   XXX  XXX   XXX  XXXXXXXXX  X  XX    XXXXX XXX   XX       XXXX  XXX  XXXX     XXXXXXXX   XXXXXX   XXXX    XXX   XX  XXXXXXX  XXXXXXXXXXXXX',
'X      XXXXXXXXX  XX  XXXXX      XX    XXXXXXXXX     XXXX  XXX   XXX  XXXXXXX   XXX  XXX   XXX  XXXXXXXXX  X  XX    XXXXX XXX   XX       XXXX  XXX  XXXX     XXXXXXXX   XXXXXX   XXXX    XXX   XX  XXXXXXX  XXXXXXXXXXXXXX',
'X      XXXXXXXXX  XX  XXXXX      XX    XXXXXXXXX     XXXX  XXX   XXX  XXXXXXX   XXX  XXX   XXX  XXXXXXXXX  X  XX    XXXXX XXX   XX       XXXX  XXX  XXXX     XXXXXXXX   XXXXXX   XXXX    XXX   XX  XXXXXXX  XXXXXXXXXXXXXX',
'X      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                                                                                                                                                               XX',
'X      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                                                                                                                                                       X   X   X XX',
'X      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                   X                                     X                          X        X                                X                         X X X X  XX',
'X                                                                  X                                       X             X           X                             X        X                 X                 X   X   XX',
'X                                                          X                    X                                                                     X     X                                     X                     XX',
'X                                        X    X     X                                   X             X                    X      X                                                                         XXXXXXXXX   XX',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                                         X                                                                                                           XXXXXXXXX   XX',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                                                                                                                                                     XXXXXXXXX   XX',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                                                                                                                                                     XXXXXXXXX   XX',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                                                                                                                                                     XXXXXXXXX   XX',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   XX',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   XX',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   XX',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   XX',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   XX',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   XX',
'                                                                                                                                                                                                                    X   XX',
'                                                                                                                                                                                                                    X   XX',
'                                                                                                                                                                                                                    X   XX',
'                                                                                                                                                                                                                    X   XX',
'                                                                                                                                                                                                                    X   XX',
'                                                                                                                                                                                                                    X   XX',
'                                                                                                                                                                                                                    X   XX',
'                                                                                                                                                                                                                    X   XX',
'                                                                                                                                                                                                                    X   XX',
'                                                                                                                                                                                                                    X   XX',
'                                                                                                                                                                                                                    X   XX',
'                                                                                                                                                                                                                    X   XX',
'                                                                                                                                                                                                                    X   XX',
'                                                                                                                                                                                                                    X   XX',
'                                                                                                                                                                                                                    X   XX',
'                                                                                                                                                                                                                    X   XX',
'                                                                                                                                                                                                                    X   XX',
'                                                                                                                                                                                                                    X   XX',
'                                                                                                                                                                                                                    X   XX',
'                                                                                                                                                                                                                    X   XX',
'                                                  XX                                                                                                                                                                X   XX',
'                                                  XX                                                                                                                                                                X   XX',
'                                                  XX                                                                                                                                                                X   XX',
'                                                  XX                                                                                                                                                                X   XX',
'                                                  XX                                                                                                                                                                X   XX',
'                                                  XX                                                                                                                                                                X   XX',
'                                                  XX                                                                                                                                                                X   XX',
'                                                  XX                                                                                                                                                                X   XX',
'                                                  XX                                                                                                                                                                X   XX',
'                                                  XX                                                                                                                                                                X   XX',
'                                                  XX                                                                                                                                                                X   XX',
'                                                  XX                                                                                                                                                                X   XX',
'                                                  XX                                                                                                                                                                X   XX',
'                                                  XX                                                                                                                                                                X   XX',
'                                                  XX                                                                                                                                                                X   XX',
'                                                  XX                                                                                                                                                                X   XX',
'                                                  XX                                                                                                                                                                X   XX',
'                                                  XX                                                                                                                                                                X   XX',
'                                                  XX                                                                                                                                                                X   XX',
'                                                  XX                                                                                                                                                                X   XX',
'                                                  XX                                                                                                                                                                    XX',
'                                                  XX                                                                                                                                                                    XX',
'                                                                                                                                                                                                                        XX',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX']

TILE_SIZE = 64
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720


BG_COLOR = '#D6EAF8'
PLAYER_COLOR = '#FF0000'
TILE_COLOR = '#AED6F1'


CAMERA_BORDERS = {
	'left': 100,
	'right': 200,
	'top':100,
	'bottom': 150
}